### ISSUE TITLE
Panic/Error during apply

### ISSUE THREAD

**Issue by jakoberpf** [tenstad/terraform-provider-remote#62]
Hi there,

i am seeing some random errors during `terraform apply`. Most of the time the `apply` is fine, but occasionally it fails. This is not a pressing issue so to say, but I also wasn't able to discover whats causing it. Happy to provide more info if I can.

### Terraform Version
`1.1.8`

### Affected Resource(s)
Please list the resources as a list, for example:
- remote_file

### Terraform Configuration Files
```hcl
resource "remote_file" "cloud_init" {
  path    = "/var/lib/vz/snippets/cloud-init-kubernetes-node-${random_string.deployment_id.result}.yml"
  content = data.template_file.cloud_init.rendered
}
```

### Expected Behavior
Resources will be created.

### Actual Behavior
Terraform panic during `terraform apply`.

```log
module.kubernetes_cluster.module.masters[1].remote_file.cloud_init: Refreshing state... [id=10.147.19.60:22:/var/lib/vz/snippets/cloud-init-kubernetes-node-3fguu.yml]
module.kubernetes_cluster.module.masters[0].remote_file.cloud_init: Refreshing state... [id=10.147.19.60:22:/var/lib/vz/snippets/cloud-init-kubernetes-node-betx0.yml]
module.kubernetes_cluster.module.masters[2].remote_file.cloud_init: Refreshing state... [id=10.147.19.60:22:/var/lib/vz/snippets/cloud-init-kubernetes-node-qnb7r.yml]
╷
│ Error: Plugin did not respond
│ 
│   with module.kubernetes_cluster.module.masters[1].remote_file.cloud_init,
│   on .terraform/modules/kubernetes_cluster.masters/cloud-init.tf line 12, in resource "remote_file" "cloud_init":
│   12: resource "remote_file" "cloud_init" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.kubernetes_cluster.module.masters[2].remote_file.cloud_init,
│   on .terraform/modules/kubernetes_cluster.masters/cloud-init.tf line 12, in resource "remote_file" "cloud_init":
│   12: resource "remote_file" "cloud_init" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.kubernetes_cluster.module.masters[0].remote_file.cloud_init,
│   on .terraform/modules/kubernetes_cluster.masters/cloud-init.tf line 12, in resource "remote_file" "cloud_init":
│   12: resource "remote_file" "cloud_init" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-remote_v0.0.23 plugin:

fatal error: concurrent map writes

goroutine 73 [running]:
runtime.throw(0x10355741f, 0x15)
        runtime/panic.go:1117 +0x54 fp=0x14000278b80 sp=0x14000278b50 pc=0x102f61fa4
runtime.mapassign_faststr(0x1036cb240, 0x1400057b230, 0x1400023a2e0, 0xc, 0x1400032d180)
        runtime/map_faststr.go:211 +0x3c0 fp=0x14000278bf0 sp=0x14000278b80 pc=0x102f421d0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x1400057b1d0, 0x1400031b860, 0x3, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader_diff.go:81 +0x240 fp=0x14000278d60 sp=0x14000278bf0 pc=0x1034c6c90
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.readObjectField(0x1037c5b08, 0x1400057b1d0, 0x14000684200, 0x2, 0x2, 0x1400031abd0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader.go:236 +0x170 fp=0x14000278ef0 sp=0x14000278d60 pc=0x1034c4330
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x1400057b1d0, 0x14000684200, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader_diff.go:76 +0x3b4 fp=0x14000279060 sp=0x14000278ef0 pc=0x1034c6e04
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.readListField(0x1037c5b08, 0x1400057b1d0, 0x140002380e0, 0x1, 0x1, 0x1400032db80, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader.go:203 +0x270 fp=0x140002791d0 sp=0x14000279060 pc=0x1034c4000
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*DiffFieldReader).ReadField(0x1400057b1d0, 0x140002380e0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1037a7900, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader_diff.go:70 +0x198 fp=0x14000279340 sp=0x140002791d0 pc=0x1034c6be8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*MultiLevelFieldReader).ReadFieldMerge(0x1400062e660, 0x140002380e0, 0x1, 0x1, 0x10354adf3, 0x3, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/field_reader_multi.go:45 +0x168 fp=0x14000279480 sp=0x14000279340 pc=0x1034c93b8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0x14000550a00, 0x140002380e0, 0x1, 0x1, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:550 +0x21c fp=0x14000279590 sp=0x14000279480 pc=0x1034ddf1c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).getRaw(0x14000550a00, 0x10354b207, 0x4, 0x140005a6208, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:119 +0x5c fp=0x14000279630 sp=0x14000279590 pc=0x1034dba7c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).GetOk(0x14000550a00, 0x10354b207, 0x4, 0x10368af20, 0x140005a6288, 0x1176592d200)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource_data.go:85 +0x40 fp=0x140002796e0 sp=0x14000279630 pc=0x1034db860
github.com/tenstad/terraform-provider-remote/internal/provider.(*apiClient).getConnWithDefault(0x1400057b170, 0x1400072c000, 0x1176592d254, 0x102fb1e20, 0x1400071a0c0)
        github.com/tenstad/terraform-provider-remote/internal/provider/provider.go:92 +0x68 fp=0x14000279720 sp=0x140002796e0 pc=0x103545898
github.com/tenstad/terraform-provider-remote/internal/provider.resourceRemoteFileRead(0x1037d5ca8, 0x1400071a0c0, 0x1400072c000, 0x1036e74a0, 0x1400057b170, 0x1400070a1d0, 0x14000279858, 0x1034d9c4c)
        github.com/tenstad/terraform-provider-remote/internal/provider/resource_remote_file.go:93 +0x44 fp=0x140002797f0 sp=0x14000279720 pc=0x103548044
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000124460, 0x1037d5c38, 0x1400033e680, 0x1400072c000, 0x1036e74a0, 0x1400057b170, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:358 +0x118 fp=0x14000279860 sp=0x140002797f0 pc=0x1034d84f8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000124460, 0x1037d5c38, 0x1400033e680, 0x140004824e0, 0x1036e74a0, 0x1400057b170, 0x140007100c0, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:635 +0x160 fp=0x14000279910 sp=0x14000279860 pc=0x1034d9cf0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1400011e9f0, 0x1037d5c38, 0x1400033e680, 0x1400033e6c0, 0x103554e4e, 0x12, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:576 +0x3ac fp=0x14000279a30 sp=0x14000279910 pc=0x1034cef8c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1400011c780, 0x1037d5ce0, 0x1400033e680, 0x1400009d440, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:553 +0x254 fp=0x14000279b20 sp=0x14000279a30 pc=0x1033b5134
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x103782d40, 0x1400011c780, 0x1037d5ce0, 0x140003410e0, 0x1400009d3e0, 0x0, 0x1037d5ce0, 0x140003410e0, 0x1400035a900, 0x81f)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c8 fp=0x14000279b90 sp=0x14000279b20 pc=0x1033a3a68
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400013a540, 0x1037dd3d8, 0x14000103980, 0x1400053c500, 0x1400031b230, 0x103c04390, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8 fp=0x14000279e40 sp=0x14000279b90 pc=0x103303f28
google.golang.org/grpc.(*Server).handleStream(0x1400013a540, 0x1037dd3d8, 0x14000103980, 0x1400053c500, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50 fp=0x14000279f60 sp=0x14000279e40 pc=0x1033075d0
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400011a1e0, 0x1400013a540, 0x1037dd3d8, 0x14000103980, 0x1400053c500)
        google.golang.org/grpc@v1.32.0/server.go:859 +0x94 fp=0x14000279fb0 sp=0x14000279f60 pc=0x103313654
runtime.goexit()
        runtime/asm_arm64.s:1130 +0x4 fp=0x14000279fb0 sp=0x14000279fb0 pc=0x102f95824
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8

goroutine 1 [select]:
github.com/hashicorp/go-plugin.Serve(0x1400019fe28)
        github.com/hashicorp/go-plugin@v1.4.1/server.go:469 +0x710
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve(0x1400010c480)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/plugin/serve.go:147 +0xb0
main.main()
        github.com/tenstad/terraform-provider-remote/main.go:47 +0x1ec

goroutine 21 [select]:
github.com/hashicorp/go-plugin.(*gRPCBrokerServer).Recv(0x1400031ae70, 0x0, 0x0, 0x0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:121 +0x6c
github.com/hashicorp/go-plugin.(*GRPCBroker).Run(0x14000122aa0)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_broker.go:411 +0x70
created by github.com/hashicorp/go-plugin.(*GRPCServer).Init
        github.com/hashicorp/go-plugin@v1.4.1/grpc_server.go:85 +0x310

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x12ad08958, 0x72, 0x1037b59d0)
        runtime/netpoll.go:227 +0x44
internal/poll.(*pollDesc).wait(0x1400010c2b8, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x1400010c2a0, 0x14000157000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x180
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0x14000680008, 0x14000157000, 0x1000, 0x1000, 0x400, 0x10369ae20, 0x1)
        os/file.go:117 +0x60
bufio.(*Reader).Read(0x1400029ff50, 0x140000e4400, 0x400, 0x400, 0x0, 0x0, 0x0)
        bufio/bufio.go:227 +0x20c
github.com/hashicorp/go-plugin.copyChan(0x1037e1328, 0x1400011c880, 0x140003488a0, 0x1037c6c88, 0x14000680008)
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:181 +0x90
created by github.com/hashicorp/go-plugin.newGRPCStdioServer
        github.com/hashicorp/go-plugin@v1.4.1/grpc_stdio.go:37 +0x94

goroutine 23 [IO wait]:
internal/poll.runtime_pollWait(0x12ad08788, 0x72, 0x1037b59d0)
        runtime/netpoll.go:227 +0x44
internal/poll.(*pollDesc).wait(0x1400010c378, 0x72, 0x1001, 0x1000, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x38
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0x1400010c360, 0x140003bf000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x180
os.(*File).read(...)
        os/file_posix.go:31
os.(*File).Read(0x14000680018, 0x140003bf000, 0x1000, 0x1000, 0x400, 0x10369ae20, 0x1)
        os/file.go:117 +0x60
bufio.(*Reader).Read(0x14000299750, 0x140000e4800, 0x400, 0x400, 0x0, 0x0, 0x0)
        bufio/bufio.go:227 +0x20c

Error: The terraform-provider-remote_v0.0.23 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by tenstad** [comment]
Thank you for creating an issue!
How many remotes files did you have configured when the problem occurred, and how many of the files should have been updated by the `terraform apply` if it had succeeded?
Does `terraform plan` also fail sometimes, or have you only experienced `terraform apply` failing?

**Comment by jakoberpf** [comment]
Did some test runs with `terraform plan` but the issue didn't occur. So it seems that it is limited to `terraform apply`.
